### ISSUE TITLE
Bug depuis PluXml 5.3

### ISSUE THREAD

**Issue by haruka-7** [Pluxopolis/plxMyAkismet#1]
Dans l'administration, à l'écran "Liste des spams", la liste des actions possibles ne s'affiche pas (à gauche du bouton "Ok") :  
![capture](https://cloud.githubusercontent.com/assets/1431205/3040941/03f58d72-e0f0-11e3-8559-d38488f6bc64.PNG)

**Comment by Deevad** [comment]
Je confirme @P3ter , j'ai le même soucis. ( je viens de mettre à jour vers 5.1.3 )
Je viens d'en faire un rapport sur le forum dans le sujet de PlxMyAkismet http://forum.pluxml.org/viewtopic.php?pid=43078#p43078 puis de découvrir que le bug était ouvert ici.

**Comment by Deevad** [comment]
Wow; un gros merci @Pluxopolis ! super rapide.
